### ISSUE TITLE
2022-08-4最新，front-project 缺少bulletins

### ISSUE THREAD

**Issue by chatgpt10** [programmermark/web-music-player#140]
### 我按照package.json里面的要求进行安装运行的时候，发现缺失文件。

- 文件：front-project/bulletins/logs/2021-08.ts
我从front中找到了这个文件后，提示缺少type类型
![image](https://user-images.githubusercontent.com/57201496/182989619-059a0307-6127-4211-995d-ecf02a721e13.png)
- 这是我的修改：import type { ILog } from "@/store/modules/interface/bulletins";

**Comment by programmermark** [comment]
你的改动是你对的。
我很久没有再关注这个项目了。
因为我最初开发这个项目时，vue的ts规则是inport接口即可，后面改动为只作为类型引入。
也就是说，这个问题是我迁移时没有修复的，你的改动是正确的。
