### ISSUE TITLE
滚动条有点问题

### ISSUE THREAD

**Issue by syt-honey** [programmermark/web-music-player#57]
#### 问题描述

打开一个页面时，一直往下滚动会出现大面积空白。猜测是滚动条的计算有点问题，似乎是出现了两个滚动条，滚动条前后颜色色值不同。

#### 复现步骤

1. 打开首页链接：https://music-player.immortalboy.cn/
2. 点击排行榜 tab
3. 点击“飙升榜”查看全部列表
4. 一直往下滑，会出现大片空白

注意：以上步骤全程不要刷新页面。

#### 设备信息

OS: macOS Big Sur 11.2.3
Browser: 91.0.4472.114（正式版本） (x86_64)

**Comment by programmermark** [comment]
这里我使用了element-plus的滚动条组件，确实存在问题，当数据还未渲染完毕事会出现大片空白；
这个问题应该在别的页面也会有，我会着手处理。感谢提出问题，帮助改进

**Comment by programmermark** [comment]
这里的问题是因为在设置滚动条的时候，历史代码中首先使用`overflow: auto;`使用原生的滚动条，后又引入了element-plus的scroll-bar组件，覆盖了`<el-scroll-bar>`的`overflow: hidden;`导致了问题。
